// Batch : 52 
// Authors
// Deepikaa Suresh : 2008B4A7552
// Nitin Gangahar : 2008B4A7733 
#include "lexer.h"
#include "parser.h"
#include "ast.h"
#include <stdio.h>
#include <stdlib.h>
extern char input_file[30];
char test_file[30];
char output_file[30];
parseTree p;
int main(int argc, char **argv) {
	if(argc < 4) {
		printf("Invalid usage : Correct usage is ./stage1exe testcase.txt cleanCode.txt parsetreeOutFile.txt\n");
	}
	printf("Press option for the defined task\n");	
	printf("1 for  printing the token list (on the console) generated by the lexer\n");
	printf("2 for producing clean code by removal of comments\n");
        printf("3 for parsing to verify the syntactic correctness of the input source code and to produce parse tree\n");
	printf("Enter : ");
	int option;
	scanf("%d", &option);
	strcpy(test_file, argv[1]);
	strcpy(input_file, argv[2]);
	strcpy(output_file, argv[3]);
	removeComments(test_file, input_file);
	
	if(option == 1) {	
		print_token_list();
	}
	else if(option == 2){
		printf("Comments removed\n");
	}
	else if(option == 3) {
		createParseTable(T);	
		p = parseInputSourceCode(input_file, T);
		printParseTree(p, output_file);
		printf("\n");
	}
	AST ast = (AST)construct(p);
	printAST(ast);
	return 0;
}
